"""
Generate db/02_seed_countries.sql from the WHR CSV.

Idee: Jeder WHR-Anzeigename bekommt eine eindeutige ISO-3166-1 alpha-3.
Damit ist die Land-Identität projektweit stabil — egal, ob WHR im
nächsten Jahr "Republic of Korea" oder "South Korea" schreibt.

Gegenmaßnahme zu:
  F3  Swaziland -> Eswatini  (beide Namen → SWZ)
  F4  Nicht-ISO-Anzeigenamen (Taiwan, Hong Kong, Palestine, Korea)
  F5  Unicode-Apostroph in "Côte d'Ivoire"
"""
from __future__ import annotations
import pandas as pd
import pycountry
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV  = ROOT / "data" / "world_happiness_data_2011_2025.csv"
OUT  = ROOT / "db" / "02_seed_countries.sql"

# Manuelle Overrides: WHR-spezifische Schreibweisen, die pycountry
# nicht (zuverlässig) auflöst. Bewusst klein gehalten und kommentiert,
# damit jede Ausnahme begründet ist.
MANUAL: dict[str, str] = {
    "Czechia":                   "CZE",
    "Eswatini":                  "SWZ",
    "Swaziland":                 "SWZ",   # F3: alte Bezeichnung, gleiches Land
    "Hong Kong SAR of China":    "HKG",
    "North Macedonia":           "MKD",
    "Republic of Korea":         "KOR",
    "South Korea":               "KOR",
    "State of Palestine":        "PSE",
    "Palestinian Territories":   "PSE",
    "Taiwan Province of China":  "TWN",
    "Taiwan":                    "TWN",
    "Turkiye":                   "TUR",
    "Türkiye":                   "TUR",
    "Turkey":                    "TUR",
    "Congo (Brazzaville)":       "COG",
    "Congo":                     "COG",
    "DR Congo":                  "COD",
    "Congo (Kinshasa)":          "COD",
    "Ivory Coast":               "CIV",
    "Côte d'Ivoire":             "CIV",   # ASCII apostrophe
    "Côte d\u2019Ivoire":        "CIV",   # F5: U+2019 (curly)
    "Myanmar":                   "MMR",
    "Burma":                     "MMR",
    "Cape Verde":                "CPV",
    "Cabo Verde":                "CPV",
    "Laos":                      "LAO",
    "Russia":                    "RUS",
    "Iran":                      "IRN",
    "Syria":                     "SYR",
    "Vietnam":                   "VNM",
    "Bolivia":                   "BOL",
    "Venezuela":                 "VEN",
    "Moldova":                   "MDA",
    "Tanzania":                  "TZA",
    "Lao PDR":                   "LAO",
    # De-facto-Entitäten, keine ISO-Codes: ISO 3166-1 reserviert XA-XZ
    # für privaten Gebrauch. Wir nutzen das konsequent und dokumentieren.
    "Kosovo":                    "XKX",   # weit verbreiteter de-facto-Code
    "North Cyprus":              "XNC",
    "Somaliland Region":         "XSL",
}

def resolve_iso3(name: str) -> str | None:
    if name in MANUAL:
        return MANUAL[name]
    # exact, dann fuzzy
    try:
        return pycountry.countries.lookup(name).alpha_3
    except LookupError:
        pass
    try:
        hits = pycountry.countries.search_fuzzy(name)
        return hits[0].alpha_3 if hits else None
    except LookupError:
        return None

def main() -> int:
    df = pd.read_csv(CSV, encoding="utf-8-sig")
    names = sorted(df["Country name"].unique())

    rows: list[tuple[str, str]] = []
    unresolved: list[str] = []
    for n in names:
        iso = resolve_iso3(n)
        if iso is None:
            unresolved.append(n)
        else:
            rows.append((n, iso))

    if unresolved:
        print("UNRESOLVED (Pipeline würde stoppen):", file=sys.stderr)
        for n in unresolved:
            print(f"  - {n!r}  hex={n.encode('utf-8').hex()}", file=sys.stderr)
        return 1

    # Eindeutige ISO3 -> kanonischer Name (kürzester pycountry-Name, fällt
    # auf den WHR-Namen zurück, wenn pycountry keinen sauberen liefert).
    iso_to_canonical: dict[str, str] = {}
    for whr_name, iso in rows:
        if iso in iso_to_canonical:
            continue
        try:
            iso_to_canonical[iso] = pycountry.countries.get(alpha_3=iso).name
        except Exception:
            iso_to_canonical[iso] = whr_name

    # SQL schreiben
    lines = [
        "-- AUTO-GENERATED by scripts/generate_country_seed.py — do not edit by hand.",
        "-- Quelle: pycountry + manuelle Overrides (siehe Script).",
        "-- Idempotent: ON CONFLICT DO UPDATE.",
        "",
        "BEGIN;",
        "",
        "-- 1) Kanonische Länder (eindeutig per ISO-3166-1 alpha-3)",
        "INSERT INTO country (iso3, canonical_name) VALUES",
    ]
    items = sorted(iso_to_canonical.items())
    for i, (iso, cname) in enumerate(items):
        cname_sql = cname.replace("'", "''")
        sep = "," if i < len(items) - 1 else ""
        lines.append(f"  ('{iso}', '{cname_sql}'){sep}")
    lines += [
        "ON CONFLICT (iso3) DO UPDATE SET canonical_name = EXCLUDED.canonical_name;",
        "",
        "-- 2) Aliase: jeder im WHR vorkommende Anzeigename → ISO3",
        "INSERT INTO country_alias (alias, iso3) VALUES",
    ]
    for i, (whr_name, iso) in enumerate(sorted(rows)):
        alias_sql = whr_name.replace("'", "''")
        sep = "," if i < len(rows) - 1 else ""
        lines.append(f"  ('{alias_sql}', '{iso}'){sep}")
    lines += [
        "ON CONFLICT (alias) DO UPDATE SET iso3 = EXCLUDED.iso3;",
        "",
        "COMMIT;",
        "",
    ]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"OK: {len(iso_to_canonical)} Länder, {len(rows)} Aliase → {OUT}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
