services:
  rainforest:
    image: swrobutsdocker/rainforest:latest
    restart: unless-stopped
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=root_default"
      # HTTP → HTTPS redirect
      - "traefik.http.routers.rainforest-http.rule=Host(`rainforest.butscher.cloud`)"
      - "traefik.http.routers.rainforest-http.entrypoints=web"
      - "traefik.http.routers.rainforest-http.middlewares=rainforest-https-redirect"
      - "traefik.http.middlewares.rainforest-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.rainforest-https-redirect.redirectscheme.permanent=true"
      # HTTPS
      - "traefik.http.routers.rainforest.rule=Host(`rainforest.butscher.cloud`)"
      - "traefik.http.routers.rainforest.entrypoints=websecure"
      - "traefik.http.routers.rainforest.tls=true"
      - "traefik.http.routers.rainforest.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.rainforest.tls.domains[0].main=rainforest.butscher.cloud"
      - "traefik.http.services.rainforest.loadbalancer.server.port=8050"
    networks:
      - traefik_net

networks:
  traefik_net:
    external: true
    name: root_default
